# Generated by Django 2.1.7 on 2019-03-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20190305_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
